services:

  backend:
    build: .
    volumes:
      - .:/app

  mailpit:  # https://mailpit.axllent.org/docs/install/docker/#docker-compose-example
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    depends_on:
      - backend
